repos:
- repo: https://github.com/psf/black
  rev: "24.2.0"
  hooks:
  - id: black
    language_version: python3.10
    args: ["--config", "csv_gp_python/pyproject.toml"]
- repo: https://github.com/pycqa/isort
  rev: "5.13.2"
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-docstring-first
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: name-tests-test
    args: [ "--pytest-test-first" ]
  # - id: no-commit-to-branch
  - id: check-added-large-files
    args: ["--maxkb=2048"]
-   repo: https://github.com/doublify/pre-commit-rust
    rev: "v1.0"
    hooks:
    - id: fmt
    - id: clippy
      args: ["--all-targets", "--", "-D", "warnings"]
