class CSVDetails:
    @property
    def row_count(self) -> int: ...
    @property
    def column_count(self) -> int: ...
    @property
    def invalid_character_count(self) -> int: ...
    @property
    def column_count_per_line(self) -> list[int]: ...
    @property
    def too_few_columns(self) -> list[int]: ...
    @property
    def too_many_columns(self) -> list[int]: ...
    @property
    def quoted_delimiter(self) -> list[int]: ...
    @property
    def quoted_newline(self) -> list[int]: ...
    @property
    def quoted_quote(self) -> list[int]: ...
    @property
    def quoted_quote_correctly(self) -> list[int]: ...
    @property
    def incorrect_cell_quote(self) -> list[int]: ...
    @property
    def all_empty_rows(self) -> list[int]: ...

def check_file(path: str, delimiter: str, encoding: str) -> CSVDetails: ...
