name: Publish

on:
  push:
    tags:
      - v*

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -m csv_gp_python/Cargo.toml --sdist --out dist
      - name: Publish wheel
        run: |
          export TWINE_USERNAME=aws
          export TWINE_PASSWORD=`aws codeartifact get-authorization-token --domain xelix --domain-owner 286666724669 --region eu-west-2 --query authorizationToken --output text`
          export TWINE_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain xelix --domain-owner 286666724669 --repository xelix --region eu-west-2 --format pypi --query repositoryEndpoint --output text`
          pip install --upgrade twine
          twine upload --skip-existing dist/*
